# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# More versions available at: https://grayray75.github.io/LegacyFabric-Versions/
# Fabric Properties
	minecraft_version = b1.7.3
	mappings_build = 23
	loader_version = 0.16.14
	nests_build = 7
	raven_build = 2
	sparrow_build = 2
	osl_version = 0.13.1

# Mod Properties
	mod_version = 1.2.6-beta.6
	maven_group = io.github.moehreag
	archives_base_name = legacy-lwjgl3
    lwjgl_version = 3.3.5
environment = client